# paths to include during linting. `--path` is ignored if present.
included:
  - ios-rentor

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - ios-rentor/Pods
  - force_cast
  - ios-rentor/AppDelegates/SceneDelegate.swift
  - ios-rentor/AppDelegates/AppDelegate.swift
    
# Configuring rule severity
force_cast: warning
force_try: warning
line_length:
  warning: 120
  error: 99999

disabled_rules:
  - identifier_name
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
